name: Update FireHOL Level 1

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download FireHOL Level 1
        run: |
          curl -o firehol_mikrotik.rsc https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset

      - name: Commit updated file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add firehol_mikrotik.rsc
          git commit -m "Update FireHOL Level 1"
          git push
