/system script add name=auto_firehol_update source="
/log info \"FIREHOL UPDATE START\"

/ip firewall address-list remove [find list=global_Blacklist]

/tool fetch url=\"https://raw.githubusercontent.com/feomin626/mikrotik-firehol/refs/heads/main/firehol_mikrotik.rsc\" dst-path=firehol_update.rsc

/import file-name=firehol_update.rsc

/ip firewall address-list remove [find list=global_Blacklist address=\"0.0.0.0/8\"]
/ip firewall address-list remove [find list=global_Blacklist address~\"10.\"] 
/ip firewall address-list remove [find list=global_Blacklist address=\"127.0.0.0/8\"]
/ip firewall address-list remove [find list=global_Blacklist address=\"169.254.0.0/16\"]
/ip firewall address-list remove [find list=global_Blacklist address=\"172.16.0.0/12\"]
/ip firewall address-list remove [find list=global_Blacklist address=\"192.168.0.0/16\"]

/log info \"FIREHOL UPDATE DONE\"
"
